CHUNK_SIZE = 1500
CHUNK_OVERLAP = 300
# SIMILARITY_THRESHOLD = 0.7
QDRANT_TIMEOUT = 120  # Timeout in seconds
EMBEDDING_MODEL ="text-embedding-3-large"
COLLECTION_NAME="chai-code-docs"
MAX_CONTEXT_CHUNKS=3